import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'bin/cli': 'src/bin/cli.ts',
    'lib/ui': 'src/lib/ui.ts',
    'lib/pm': 'src/lib/pm.ts',
    'lib/checker': 'src/lib/checker.ts',
    'lib/fixer': 'src/lib/fixer.ts',
    'lib/ejector': 'src/lib/ejector.ts',
    'lib/builder': 'src/lib/builder.ts',
    'lib/dev': 'src/lib/dev.ts',
    'lib/start': 'src/lib/start.ts',
    'lib/updateNotifier': 'src/lib/updateNotifier.ts',
    'lib/moduleGenerator': 'src/lib/moduleGenerator.ts',
    'lib/authGenerator': 'src/lib/authGenerator.ts',
    'lib/agentDocsGenerator': 'src/lib/agentDocsGenerator.ts',
    'lib/readmeGenerator': 'src/lib/readmeGenerator.ts',
    'lib/dockerScaffold': 'src/lib/dockerScaffold.ts',
    'lib/remover': 'src/lib/remover.ts',
    'lib/lister': 'src/lib/lister.ts',
    'lib/envGenerator': 'src/lib/envGenerator.ts',
    'lib/middlewareGenerator': 'src/lib/middlewareGenerator.ts',
    'lib/configLoader': 'src/lib/configLoader.ts',
    'lib/db/index': 'src/lib/db/index.ts',
    'lib/db/mongoose': 'src/lib/db/mongoose.ts',
    'lib/db/prisma': 'src/lib/db/prisma.ts',
    'lib/db/drizzle': 'src/lib/db/drizzle.ts',
    'lib/validator/index': 'src/lib/validator/index.ts',
    'lib/validator/zod': 'src/lib/validator/zod.ts',
    'lib/validator/joi': 'src/lib/validator/joi.ts',
    'lib/core/scaffoldCore': 'src/lib/core/scaffoldCore.ts',
    'lib/core/globalErrorHandler/shell': 'src/lib/core/globalErrorHandler/shell.ts',
  },
  format: ['cjs'],
  clean: true,
  dts: false,
  minify: true,
  sourcemap: false,
  treeshake: true,
  shims: true,
  noExternal: ['inquirer'],
});
