'use strict';

const fs = require('fs');
const path = require('path');
const { runScript } = require('./pm');

// ─── HELPERS ─────────────────────────────────────────────────────────────────

function dbLabel(db) {
    return {
        mongoose: 'Mongoose (MongoDB)',
        prisma: 'Prisma (PostgreSQL)',
        drizzle: 'Drizzle (PostgreSQL)',
    }[db] || db;
}

function modelPattern(db) {
    switch (db) {
        case 'mongoose':
            return 'Mongoose schemas — `new Schema<IModel>({...})` exported as `model<IModel>(\'Name\', schema)`';
        case 'prisma':
            return 'Prisma schema — models defined in `prisma/schema.prisma`, accessed via singleton `prisma` client in `src/app/utils/prisma.ts`';
        case 'drizzle':
            return 'Drizzle schemas — tables defined with `pgTable()` in model files, accessed via `drizzle(pool)` in `src/app/utils/drizzle.ts`';
        default:
            return '';
    }
}

function modelExample(db, moduleName) {
    const lower = moduleName.toLowerCase();

    switch (db) {
        case 'mongoose':
            return `\`\`\`ts
// src/app/modules/${moduleName}/${lower}.model.ts
import { Schema, model } from 'mongoose';
import { I${moduleName} } from './${lower}.interface';

const ${lower}Schema = new Schema<I${moduleName}>(
  {
    name: { type: String, required: true },
    // ... fields
  },
  { timestamps: true },
);

export const ${moduleName} = model<I${moduleName}>('${moduleName}', ${lower}Schema);
\`\`\``;

        case 'prisma':
            return `\`\`\`prisma
// prisma/schema.prisma
model ${moduleName} {
  id        String   @id @default(cuid())
  name      String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
\`\`\`

Then access via:
\`\`\`ts
import { prisma } from '../../utils/prisma';
const items = await prisma.${lower}.findMany();
\`\`\``;

        case 'drizzle':
            return `\`\`\`ts
// src/app/modules/${moduleName}/${lower}.model.ts
import { pgTable, text, timestamp, varchar } from 'drizzle-orm/pg-core';
import crypto from 'crypto';

export const ${lower}s = pgTable('${lower}s', {
  id:        text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  name:      varchar('name', { length: 255 }).notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});
\`\`\``;
        default:
            return '';
    }
}

function validationExample(validator, moduleName) {
    const lower = moduleName.toLowerCase();

    if (validator === 'zod') {
        return `\`\`\`ts
// src/app/modules/${moduleName}/${lower}.validation.ts
import { z } from 'zod';

const create${moduleName}Schema = z.object({
  body: z.object({
    name: z.string().min(1, 'Name is required'),
  }),
});

export const ${moduleName}Validation = { create${moduleName}Schema };
\`\`\``;
    }

    return `\`\`\`ts
// src/app/modules/${moduleName}/${lower}.validation.ts
import Joi from 'joi';

const create${moduleName}Schema = Joi.object({
  name: Joi.string().required().min(1),
});

export const ${moduleName}Validation = { create${moduleName}Schema };
\`\`\``;
}

function migrationCmd(db, pm) {
    switch (db) {
        case 'mongoose':
            return null; // Mongoose auto-syncs
        case 'prisma':
            return `${pm === 'npm' ? 'npx' : pm === 'yarn' ? 'yarn' : 'pnpm exec'} prisma migrate dev --name <migration_name>`;
        case 'drizzle':
            return `${pm === 'npm' ? 'npx' : pm === 'yarn' ? 'yarn' : 'pnpm exec'} drizzle-kit migrate`;
        default:
            return null;
    }
}

// ─── AGENTS.MD ───────────────────────────────────────────────────────────────

function buildAgentsMd(opts) {
    const {
        projectName, db, validator, useAuth, useDocker, tokenDelivery, pm = 'npm',
    } = opts;

    const lines = [];

    lines.push(`# AGENTS.md`);
    lines.push('');
    lines.push(`> Auto-generated by [create-express-modular](https://create-express-modular.lovable.app/). This file helps AI coding assistants understand the project.`);
    lines.push('');

    // ── Identity ─────────────────────────────────────────────────────────────
    lines.push(`## Project: ${projectName}`);
    lines.push('');
    lines.push(`A production-ready, domain-driven **Express + TypeScript** backend.`);
    lines.push('');

    // ── Stack ────────────────────────────────────────────────────────────────
    lines.push('## Tech Stack');
    lines.push('');
    lines.push(`- **Runtime**: Node.js ≥ 18`);
    lines.push(`- **Framework**: Express`);
    lines.push(`- **Language**: TypeScript (strict)`);
    lines.push(`- **Database / ORM**: ${dbLabel(db)}`);
    lines.push(`- **Validation**: ${validator === 'zod' ? 'Zod' : 'Joi'}`);
    lines.push(`- **Package Manager**: ${pm}`);
    if (useAuth) {
        const delivery = tokenDelivery === 'cookie' ? 'HTTP-only cookies' : 'Authorization header';
        lines.push(`- **Auth**: JWT with bcrypt + rate limiting (${delivery})`);
    }
    if (useDocker) {
        lines.push(`- **Docker**: Dockerfile + docker-compose`);
    }
    lines.push('');

    // ── Architecture Rules ──────────────────────────────────────────────────
    lines.push('## Architecture Rules');
    lines.push('');
    lines.push('1. All source code lives under `src/`.');
    lines.push('2. **Modules** follow domain-driven design: `src/app/modules/<Name>/` with files named `<name>.controller.ts`, `<name>.service.ts`, `<name>.route.ts`, `<name>.model.ts`, `<name>.interface.ts`, `<name>.validation.ts`.');
    lines.push('3. **Middleware** files MUST be named `<name>.middleware.ts` inside `src/app/middlewares/`. The build will fail otherwise.');
    lines.push('4. Routes are auto-registered in `src/app/routes/index.ts` via inject markers (`// --- INJECT IMPORTS HERE ---` and `// --- INJECT ROUTES HERE ---`). Do NOT remove these markers.');
    lines.push('5. **All environment variables** go through `src/app/config/index.ts` — never use `process.env` directly in application code.');
    lines.push('6. Wrap all async route handlers with `catchAsync()` from `src/app/utils/catchAsync.ts`.');
    lines.push('7. Use `sendResponse()` from `src/app/utils/sendResponse.ts` for all API responses.');
    lines.push('8. Use `validateRequest()` middleware to validate incoming request bodies against schemas.');

    if (db === 'mongoose') {
        lines.push('9. Use `QueryBuilder` from `src/app/utils/QueryBuilder.ts` for search, filter, sort, and pagination on Mongoose queries.');
    }

    lines.push('');

    // ── Model Pattern ───────────────────────────────────────────────────────
    lines.push('## Model Pattern');
    lines.push('');
    lines.push(modelPattern(db));
    lines.push('');

    // ── CLI Commands ────────────────────────────────────────────────────────
    lines.push('## CLI Commands');
    lines.push('');
    lines.push('Use the CEM CLI for scaffolding — do NOT create module/middleware files manually.');
    lines.push('');
    lines.push('| Command | Effect |');
    lines.push('|---|---|');
    lines.push('| `cem add module <Name...>` | Scaffold module(s) with all files + auto-wire routes |');
    lines.push('| `cem add middleware <name...>` | Create middleware file(s) with correct naming |');
    lines.push('| `cem add env <KEY...>` | Add env var(s) to `.env`, `.env.example`, and `config/index.ts` |');
    lines.push('| `cem remove module <Name>` | Delete module + unwire route |');
    lines.push('| `cem remove middleware <name>` | Delete middleware file |');
    lines.push('| `cem remove env <KEY>` | Remove env var from all config files |');
    lines.push('| `cem dev` | Start dev server with hot reload |');
    lines.push('| `cem build` | Convention guards + TypeScript compilation |');
    lines.push('| `cem check` | Type-check + lint + format check |');
    lines.push('');

    const migrate = migrationCmd(db, pm);
    if (migrate) {
        lines.push('## Database Migrations');
        lines.push('');
        lines.push('```bash');
        lines.push(migrate);
        lines.push('```');
        lines.push('');
    }

    // ── Don'ts ──────────────────────────────────────────────────────────────
    lines.push('## Do NOT');
    lines.push('');
    lines.push('- Create module files manually — use `cem add module`.');
    lines.push('- Use `process.env` directly — import `config` from `src/app/config`.');
    lines.push('- Rename middleware files without the `.middleware.ts` suffix — `cem build` will reject it.');
    lines.push('- Remove the inject markers in `src/app/routes/index.ts`.');
    lines.push('- Modify core middlewares (`globalErrorHandler`, `notFound`' + (useAuth ? ', `auth`, `rateLimiter`' : '') + ') unless intentional.');
    lines.push('');

    return lines.join('\n');
}

// ─── CLAUDE.MD ───────────────────────────────────────────────────────────────

function buildClaudeMd(opts) {
    const {
        projectName, db, validator, useAuth, useDocker, tokenDelivery, pm = 'npm',
    } = opts;

    const lines = [];

    lines.push('# CLAUDE.md');
    lines.push('');
    lines.push(`> Project-specific context for Claude. Auto-generated by [create-express-modular](https://create-express-modular.lovable.app/).`);
    lines.push('');

    // ── Overview ─────────────────────────────────────────────────────────────
    lines.push(`## Overview`);
    lines.push('');
    lines.push(`**${projectName}** is a production-ready Express + TypeScript backend built with the \`create-express-modular\` (CEM) CLI.`);
    lines.push('');
    lines.push(`| Layer | Choice |`);
    lines.push(`|---|---|`);
    lines.push(`| Database / ORM | ${dbLabel(db)} |`);
    lines.push(`| Validation | ${validator === 'zod' ? 'Zod' : 'Joi'} |`);
    lines.push(`| Package Manager | ${pm} |`);
    if (useAuth) {
        const delivery = tokenDelivery === 'cookie' ? 'HTTP-only cookies' : 'Authorization header';
        lines.push(`| Auth | JWT + bcrypt (${delivery}) |`);
    }
    if (useDocker) {
        lines.push(`| Docker | Yes |`);
    }
    lines.push('');

    // ── Project Structure ───────────────────────────────────────────────────
    lines.push('## Project Structure');
    lines.push('');
    lines.push('```');
    lines.push('src/');
    lines.push('├── app/');
    lines.push('│   ├── config/index.ts           # Centralized config — ALL env vars');
    lines.push('│   ├── errors/                    # AppError + DB-specific error handlers');
    lines.push('│   ├── interfaces/                # Shared TypeScript types');
    lines.push('│   ├── middlewares/                # <name>.middleware.ts (strict naming)');
    lines.push('│   ├── modules/                   # Domain modules (<Name>/ directories)');
    lines.push('│   ├── routes/index.ts            # Auto-wired route registry');
    lines.push('│   └── utils/                     # catchAsync, sendResponse, validateRequest, logger');
    lines.push('├── app.ts                         # Express app setup');
    lines.push('└── server.ts                      # DB connection + server bootstrap');
    lines.push('```');
    lines.push('');

    // ── Module Anatomy ──────────────────────────────────────────────────────
    lines.push('## Module Anatomy');
    lines.push('');
    lines.push('Every feature module lives in `src/app/modules/<Name>/` and contains:');
    lines.push('');
    lines.push('| File | Purpose |');
    lines.push('|---|---|');
    lines.push('| `<name>.interface.ts` | TypeScript interface / types |');
    lines.push('| `<name>.model.ts` | Database model / schema |');
    lines.push('| `<name>.validation.ts` | Request validation schemas |');
    lines.push('| `<name>.service.ts` | Business logic (DB operations) |');
    lines.push('| `<name>.controller.ts` | Request handlers (uses `catchAsync` + `sendResponse`) |');
    lines.push('| `<name>.route.ts` | Express router |');
    lines.push('| `<name>.constant.ts` | *(optional)* ENUMs, searchable fields |');
    lines.push('| `<name>.utils.ts` | *(optional)* Module-specific helpers |');
    lines.push('');

    // ── Key Patterns ────────────────────────────────────────────────────────
    lines.push('## Key Patterns');
    lines.push('');

    // Controller pattern
    lines.push('### Controller Pattern');
    lines.push('');
    lines.push('```ts');
    lines.push('import { Request, Response } from \'express\';');
    lines.push('import { catchAsync } from \'../../utils/catchAsync\';');
    lines.push('import sendResponse from \'../../utils/sendResponse\';');
    lines.push('import { StatusCodes } from \'http-status-codes\';');
    lines.push('');
    lines.push('const createItem = catchAsync(async (req: Request, res: Response) => {');
    lines.push('  const result = await ItemService.create(req.body);');
    lines.push('  sendResponse(res, {');
    lines.push('    statusCode: StatusCodes.CREATED,');
    lines.push('    success: true,');
    lines.push('    message: \'Item created successfully\',');
    lines.push('    data: result,');
    lines.push('  });');
    lines.push('});');
    lines.push('```');
    lines.push('');

    // Model pattern
    lines.push('### Model Pattern');
    lines.push('');
    lines.push(modelExample(db, 'Item'));
    lines.push('');

    // Validation pattern
    lines.push('### Validation Pattern');
    lines.push('');
    lines.push(validationExample(validator, 'Item'));
    lines.push('');

    // Route pattern
    lines.push('### Route Pattern');
    lines.push('');
    lines.push('```ts');
    lines.push('import express from \'express\';');
    lines.push('import { ItemControllers } from \'./item.controller\';');
    lines.push('import validateRequest from \'../../utils/validateRequest\';');
    lines.push('import { ItemValidation } from \'./item.validation\';');
    if (useAuth) {
        lines.push('import auth from \'../../middlewares/auth.middleware\';');
    }
    lines.push('');
    lines.push('const router = express.Router();');
    lines.push('');
    if (useAuth) {
        lines.push('router.post(');
        lines.push('  \'/\',');
        lines.push('  auth(\'USER\'),');
        lines.push('  validateRequest(ItemValidation.createItemSchema),');
        lines.push('  ItemControllers.createItem,');
        lines.push(');');
        lines.push('router.get(\'/\', auth(\'USER\', \'ADMIN\'), ItemControllers.getAllItems);');
    } else {
        lines.push('router.post(');
        lines.push('  \'/\',');
        lines.push('  validateRequest(ItemValidation.createItemSchema),');
        lines.push('  ItemControllers.createItem,');
        lines.push(');');
        lines.push('router.get(\'/\', ItemControllers.getAllItems);');
    }
    lines.push('');
    lines.push('export const ItemRoutes = router;');
    lines.push('```');
    lines.push('');

    // ── Environment Variables ────────────────────────────────────────────────
    lines.push('## Environment Variables');
    lines.push('');
    lines.push('All env vars are centralized in `src/app/config/index.ts`. To add a new one:');
    lines.push('');
    lines.push('```bash');
    lines.push('cem add env STRIPE_SECRET_KEY');
    lines.push('```');
    lines.push('');
    lines.push('This updates `.env`, `.env.example`, and `config/index.ts` in one step. Then import:');
    lines.push('');
    lines.push('```ts');
    lines.push('import config from \'./app/config\';');
    lines.push('console.log(config.stripe_secret_key);');
    lines.push('```');
    lines.push('');

    // ── Auth (conditional) ──────────────────────────────────────────────────
    if (useAuth) {
        lines.push('## Authentication');
        lines.push('');
        lines.push(`This project uses JWT authentication with **${tokenDelivery === 'cookie' ? 'HTTP-only cookie' : 'Authorization header'}** token delivery.`);
        lines.push('');
        lines.push('### Protecting a Route');
        lines.push('');
        lines.push('```ts');
        lines.push('import auth from \'../../middlewares/auth.middleware\';');
        lines.push('');
        lines.push('// Single role');
        lines.push('router.get(\'/admin\', auth(\'ADMIN\'), controller.adminOnly);');
        lines.push('');
        lines.push('// Multiple roles');
        lines.push('router.get(\'/dashboard\', auth(\'USER\', \'ADMIN\'), controller.dashboard);');
        lines.push('```');
        lines.push('');
        lines.push('### Core auth files');
        lines.push('');
        lines.push('- `src/app/modules/Auth/` — Controller, service, model, validation, route');
        lines.push('- `src/app/middlewares/auth.middleware.ts` — JWT verification + role guard');
        lines.push('- `src/app/middlewares/rateLimiter.middleware.ts` — Global + login rate limiters');
        lines.push('');
    }

    // ── Build & Quality ─────────────────────────────────────────────────────
    lines.push('## Build & Quality');
    lines.push('');
    lines.push('| Command | What it does |');
    lines.push('|---|---|');
    lines.push('| `cem dev` | Start dev server (tsx, hot reload) |');
    lines.push('| `cem build` | Middleware naming guard → Architecture guard → `tsc` |');
    lines.push('| `cem check` | Type-check → ESLint → Prettier |');
    lines.push('| `cem start` | Production server with preflight checks |');
    lines.push(`| \`${runScript(pm, 'lint:fix')}\` | Auto-fix lint issues |`);
    lines.push(`| \`${runScript(pm, 'prettier:fix')}\` | Auto-format code |`);
    lines.push('');

    const migrate = migrationCmd(db, pm);
    if (migrate) {
        lines.push('## Database Migrations');
        lines.push('');
        lines.push('```bash');
        lines.push(migrate);
        lines.push('```');
        lines.push('');
    }

    // ── Docker (conditional) ────────────────────────────────────────────────
    if (useDocker) {
        lines.push('## Docker');
        lines.push('');
        lines.push('```bash');
        lines.push('# Dev (app + database sidecar)');
        lines.push('docker-compose up --build');
        lines.push('');
        lines.push('# Production');
        lines.push(`docker build -t ${projectName} .`);
        lines.push(`docker run -p 5000:5000 --env-file .env ${projectName}`);
        lines.push('```');
        lines.push('');
    }

    // ── Critical Rules ──────────────────────────────────────────────────────
    lines.push('## Critical Rules');
    lines.push('');
    lines.push('- **Use CEM CLI** for scaffolding modules, middleware, and env vars — it handles file creation, naming, and route wiring automatically.');
    lines.push('- **Never use `process.env` directly** — always import from `src/app/config`.');
    lines.push('- **Middleware naming is enforced** — `<name>.middleware.ts` is mandatory. `cem build` rejects non-conforming files.');
    lines.push('- **Do not remove inject markers** in `src/app/routes/index.ts` (`// --- INJECT IMPORTS HERE ---` and `// --- INJECT ROUTES HERE ---`).');
    lines.push('- **Error handling is automatic** — the `globalErrorHandler` middleware maps ' + db + ' and ' + validator + ' errors to a consistent `{ success, message, errorSources }` JSON response.');
    lines.push('- **`catchAsync` is required** — all async Express handlers must be wrapped with it to avoid unhandled promise rejections.');
    lines.push('');

    return lines.join('\n');
}

// ─── PUBLIC API ──────────────────────────────────────────────────────────────

/**
 * Generate AGENTS.md and CLAUDE.md tailored to the scaffolded project.
 *
 * @param {string} projectPath  Absolute path to the new project directory
 * @param {object} opts
 * @param {string} opts.projectName
 * @param {string} opts.db           'mongoose' | 'prisma' | 'drizzle'
 * @param {string} opts.validator    'zod' | 'joi'
 * @param {boolean} opts.useAuth
 * @param {boolean} opts.useDocker
 * @param {string} opts.tokenDelivery 'cookie' | 'header'
 * @param {string} opts.pm           'npm' | 'yarn' | 'pnpm'
 */
function generateAgentDocs(projectPath, opts) {
    fs.writeFileSync(path.join(projectPath, 'AGENTS.md'), buildAgentsMd(opts));
    fs.writeFileSync(path.join(projectPath, 'CLAUDE.md'), buildClaudeMd(opts));
}

module.exports = { generateAgentDocs };
